image: alpine:latest

before_script: |
  apk add make

pages:
  stage: deploy
  script: |
    make
    mkdir -p ./public
    cp -r ./Build/* ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
