image: alpine:latest

before_script: |
  echo null

pages:
  stage: deploy
  script: |
    mkdir -p ./public
    cp * ./public/
    cd ./public
    sh ./Make.sh
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
